### ISSUE TITLE
Issues with the data files with names containing "<=" or ">=" for window os users

### ISSUE THREAD

**Issue by HQEM** [USEPA/CompTox-HumanExposure-bayesmarker#14]
Can not install the package from github directly. As a workaround, I download the package as a .zip file first and then installed locally. during the installation, it gave me an error message that it can not find the data file named "Stanfield2022MarkovChains/01-02/lPsamps-gm_kg_day_BMI <= 30_2021-05-11.RData". It seems that any files in the folder of 01-02 with names containing ">=" or "<=" were not being downloaded as part of the zip file. I've downloaded these missing files individually from github. The names of these files however will change to some random characters by window os. Window os does not support ">=" or "<=" in the file names. will it be possible to update these file names to something like "le" or "ge" instead? think this issue will impact all the window users. Thanks!

**Comment by jfwambaugh** [comment]
Thanks for pointing this out. I think we have fixed this (thanks to your message and help from Sashoy Milton at Duke).
